---
language: node_js
node_js:
  - "5.10"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

before_script:
  # Configuring NPM
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g phantomjs-prebuilt
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
